resolver: nightly-2024-08-25
packages:
  - '.'
extra-deps:
  - git: https://github.com/fizruk/telegram-bot-simple.git
    commit: 'f7acd0a9feb7fd9beb0ec621a2fe271f6721d51c'
    subdirs:
      - telegram-bot-simple
